### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kctess5** [goroda/c3sc#2]
Hi, there appears to be a memory leak lurking here somewhere. When I run c3sc on the examples (e.g. bin/scar) the memory usage slowly increases and progress grinds to a halt when it starts to swap. I killed it at 47 iterations and at that point it was using 30GB memory + 31GB swap.

Current workaround: repeatedly run the binary with a small number of iterations, since it reloads the previous result anyways.

Cheers!

**Comment by goroda** [comment]
Thanks for letting me know, I verified the problem occurs as well on my machine. However, I am on travel and don't have the time to fix this right now. Will get back to it in a week and let you know when it is done!

**Comment by kctess5** [comment]
No problem, enjoy your travels!

**Comment by goroda** [comment]
I fixed the problem, the memory growth should plateau now. I still do not have a good way of controlling specifically the amount of memory that you want to use. However it should be nowhere near the 30GB + 31GB swap.  For bin/scar it peaks at approximately 6.3GB. 

Please let me know if you are still running into these types of problems or notice any changes in performance due to this change.
